### ISSUE TITLE
Using Neos along with Laravel

### ISSUE THREAD

**Issue by aftabnaveed** [neos/flow-development-collection#1045]
I know its crazy to ask this question! But we have a few projects developed in Laravel and we are quite happy with it, but I really like NEOS CMS. I believe there is no match to it, and I know it is developed Flow which again is a decent framework. Since I already use Laravel I would like to keep using it, but I would like to use it along with NEOS. 

Is it something possible? I hope I am not talking crazy here :-)

**Comment by iseries** [comment]
u can not use neos with Laravel instead of flow. Neos is **build with flow** - you have to work with flow as base, if you want to develop with neos. However: Im sure that you can "connect" a laravel project with Neos by using an API but... ye.

**Comment by albe** [comment]
Yes, you can not replace the underlying Flow Framework of Neos with something else, but it should be totally doable to add application modules built in other Frameworks. At most you would need to implement a few Adapters, depending on where you want to plug your other-module, e.g. should it just be a content provider, should it be a content element or is it a "micro-service"?

If you take the attempt feel free to come over on slack.neos.io and you will surely find a couple of people willing to help you with all struggles you might come up with on that journey. If you also manage to somewhoe document/distill your experience into something shareable, that would be awesome!

**Comment by aftabnaveed** [comment]
Thank you @albe @iseries for paying attention to my question. Albe you brought an interesting point of micro-services here. All of my Laravel packages are built on that concept and has RestFul API endpoints. Now I really like the security framework of Flow, and for authentication, I would like to use that. Here I am a bit struggling to find appropriate documentation for it. Is there any documentation available for OAuth or JWT  authentications using flow some where? 

In addition to above, the concept of new rendering language (Fusion) also makes me interested, which essentially can be used to render JSON format,  but I want a fine grain control over what and which format I want to construct the JSON, something similar to this library http://fractal.thephpleague.com/simple-example/

**Comment by albe** [comment]
Yes, you should be easily able to integrate fractal and use it to transform your data to an array and return that from your controller with a set JsonView. Flow Framework supports thrid party libraries installed via composer out-of-the-box and anything else is just a matter at placing it in a properly PSR-0/4 autoloadable location.

Since Flow is an opinionated Framework, it does not provide solutions to all possible (and not even subjectively "major") problems out of the box, so for specific use cases like oauth/jwt, this depends on 3rd party packages to provide that. On top of community provided solutions, there are also a few packages maintained by Neos developers within the `Flowpack` namespace.

Here are two packages for the two topics:
https://www.neos.io/download-and-extend/packages/flowpack/flowpack-oauth2-client.html
https://www.neos.io/download-and-extend/packages/wazisera/wazisera-flow-utility-jwt.html

Feel free to ask questions on our #slack, there will be plenty of helpful people around.

**Comment by albe** [comment]
I'm closing this for now, since it was more a question rather than an outstanding issue/feature request and I hope it was answered sufficiently :)
