### ISSUE TITLE
Normalize scalar type names to the built-in PHP names

### ISSUE THREAD

**Issue by bwaidelich** [neos/flow-development-collection#1106]
The `TypeHandling::normalizeType()` utility function converts the short scalar type "int" and "bool" to their longer equivalent (see [source](https://github.com/neos/flow-development-collection/blob/master/Neos.Utility.ObjectHandling/Classes/TypeHandling.php#L76-L90)).

This should be turned around for consistency, as PHP scalar type hints also use the short notation.

Fix version: Lowest supported branch (currently Flow 3.3 LTS)

**Comment by bwaidelich** [comment]
I‘m not 100% certain if it‘s worth the breaking change to be honest and one could argue that the current behavior is in sync with PHPs ˋgettype()ˋ return values.
In any case, to fix https://github.com/neos/neos-development-collection/issues/1732 we‘ll need a different solution that works for the older branches

**Comment by kitsunet** [comment]
This is not declared public API in any case. And mostly used in conjunction with tags/annotations which again obviously are closely related to type declarations. Those again use the short form, eg. currently 

```
/**
 * @param boolean $foo
 */
function bar(bool $foo) {
```

this is our guideline. First of all we should suggest using short forms in the param tag as well. Second internally the param is currently always normalised to `boolean` whereas the type declaration is not because we need the original (and only working) string `bool` to be used in proxy classes. That's why I suggested since a while to change internal defaults to use short forms everywhere so we are consistent with the type declarations. Obviously that means a `gettype` result needs to be run through `normalizeType` as well, but we don't use gettype a lot and I think it's ok to do that.

**Comment by kitsunet** [comment]
And first of all I would strongly suggest to revert the change made tot he string converter in here:
https://github.com/neos/flow-development-collection/pull/1083

I guess somewhere another normalize call is missing if it doesn't work with `boolean`. That would be the right fix for now and then we can take our time finding a good solution for the mess...

**Comment by kdambekalns** [comment]
> as PHP scalar type hints also use the short notation

From #1109: Long and short form still work in PHP for type declarations:

    > $f = function (int $i): bool {};
    > $f = function (integer $i): boolean {};

Also, `is_integr()` still exists, even if it's not in the documentatoin anymore:

    > var_dump(is_int(1));
    bool(true)
    > var_dump(is_integer(1));
    bool(true)

The `settype()` function accepts both as well:
    
    > $var='1'; settype($var, 'int'); var_dump($var);
    int(1)
    > $var='1'; settype($var, 'integer'); var_dump($var);
    int(1)
    
And last but not least there is `gettype()`:

    > var_dump(gettype(1));
    string(7) "integer"

That returns the long form.

**Comment by bwaidelich** [comment]
@kdambekalns Thanks for collecting this information from the realms of PHP weirdness ;)
After dissecting the root cause I no longer think that we have to change the behavior of `TypeHandling::normalizeType()`. IMO it's not worth the B/C and one could argue both ways anyways..

What we _could_ think about is the `double` case that returns a `float` - which is not in sync with [PHPs gettype()](http://php.net/manual/en/function.gettype.php):

> for historical reasons "double" is returned in case of a float, and not simply "float"

doh.

Closing this for now, feel free to re-open/comment if you disagree
