### ISSUE TITLE
Central Tagging

### ISSUE THREAD

**Issue by bwaidelich** [neos/flow-development-collection#1153]
We use tagging in various places (Session, Caching, Routing, Assets, ...) but all implementations are very basic and duplicate logic.

We should consider introducing a `Tag` Value Object that can be reused for those places (and by userland code).
The advantage of a Value Object would be central solution of tasks like validation, serialization, comparison, merging of tags.

For good measure we should probably introduce tag related classes in a new package (`Neos.Tag` for example) or find an existing package that suits our needs.

**Comment by bwaidelich** [comment]
Example for a possible Tag signature:
```php
final class Tag {
  private function __construct(string $tag);

  public static function fromString(string $tag): self;

  public function equals(Tag $otherTag): bool;

  public function __toString(): string;
}
```

and there should also be a VO for `Tags` handling merging etc

**Comment by robertlemke** [comment]
I'm in favor of introducing a Tag value object for this purpose, but only for the reasons of centralized validation, serialization, comparison and so - not for deduplication. So I'd rather see separate Tag objects in each of the (sub) packages.

The packages you mention are very central to Flow, but on the other hand, they are separate packages. So you'd end up with some "common" package or "tag" package. This reminds me a bit of the DRY in micro services discussion (remember the keynote by Eric Evans?). Since I develop micro services, I have become much more cautious when I plan to implement DRY.

**Comment by bwaidelich** [comment]
@robertlemke Thanks for your comment.
I agree about the motivation: DRY should not be the main reason to introduce such a package and we should not try to create a "swiss army knife tagging manager" ;)

All I have in mind is a `Tag` VO (and maybe `Tags` for a list of tags) and maybe maybe a simple doctrine type implementation so that they can be used directly from within entities if suitable

**Comment by bwaidelich** [comment]
In the meantime I question the idea to centralize this (and thus add more inter-dependencies) – still worth considering, but as I don't plan to work on this any time soon I'll close this one for now.
Feel free to re-open if you consider this very important and/or want to work on it
