### ISSUE TITLE
Using Doctrine\Common\Persistence\ObjectManager is broken instead of deprecated

### ISSUE THREAD

**Issue by albe** [neos/flow-development-collection#1345]
Since https://github.com/neos/flow-development-collection/pull/1272 the usage of `ObjectManager` is deprecated in favor of the `EntityManagerInterface`. However, injecting the old `ObjectManager` is breaking behaviour, by no longer persisting data instead of just working correctly still.

Flow: 5.0+

What we need to do, is somehow return the same instance for `EntityManagerInterface` and doctrine `ObjectManager`, either from the `EntityManagerFactory` or the Flow `ObjectManager` directly.

**Comment by DavidSporer** [comment]
We had this problem as well. What @albe suggests would fix it IMHO. In general it is a state that shouldn't be as it is since I'd expect the deprecated ObjectManager to still work as it did.
Another question: when removing the ObjectManager does it make sense to create a code migration that replaces the ObjectManager usages with EntityManagerInterface or are there differences that you need to apply manually?

**Comment by kdambekalns** [comment]
Yep, that was a side effect that went unnoticed in the beginning and then we (I) fixed the injections in Neos and Flow code (and some of our own).

Fixing it by actually returning the same instance for both class names would be great!

**Comment by kdambekalns** [comment]
The `EntityManagerFactory` should probably still create a new instance when asked to do so, so the fix should be done in the `ObjectManager`…

**Comment by kdambekalns** [comment]
Hehe, see also https://github.com/neos/neos-development-collection/pull/2067#pullrequestreview-121477522

**Comment by albe** [comment]
I have been up to something there... :tada: :man_facepalming:  Can we just add a hardcoded check in ObjectManager for `ObjectManager` and rewrite that to `EntityManagerInterface`?
