### ISSUE TITLE
Route caches should be excluded from caches per route

### ISSUE THREAD

**Issue by johannessteu** [neos/flow-development-collection#1426]
### Description
Today all our routes are cached. This is fine as long as you do not configure `appendExceedingArguments: true`. If you do so you create a cache entry for each route. Imagine you have a page with a filter. Or a pagination like `http://webiste.com/search?p=1`. For each `p=` a cache entry (to be exact the uri constraints) will be created. This can blow up your cache backend very easily.

#### Expected behavior
To avoid this a route should be able to excluded itself from caching. This could be done with a config option per route like
```
-
  name: 'Search with pagination'
  uriPattern: 'search?p={currentPage}'
  defaults:
    '@package': 'Some.Package'
    '@controller': 'Search'
    '@action': 'index'
    '@format': 'html'
  appendExceedingArguments: true
  cache: false
```

**Comment by Torsten85** [comment]
@kitsunet are you sure that exceedingArguments are not cached?
This line https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Mvc/Routing/Router.php#L198 stores resolved uri constraints and I think those include the resolved path (https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Mvc/Routing/Route.php#L541). Or am I missing something here?

**Comment by kitsunet** [comment]
Ah, paging @bwaidelich IMHO that shouldn't happen and I am relatively sure it didn't in the past.

**Comment by johannessteu** [comment]
Updated the issue msg to the pagination case wich makes much more sense as the appendExceedingArguments are only used for the resolve path.

**Comment by bwaidelich** [comment]
Don't use `appendExceedingArguments` for that. They are meant for a fixed set of arguments that should be mapped to query parameters and thus they are cached.
A search phrase is *not* a routing argument:

```
-
  name: 'Search with pagination'
  uriPattern: 'search'
  defaults:
    '@package': 'Some.Package'
    '@controller': 'Search'
    '@action': 'index'
    '@format': 'html'
```
and in Fluid:
```
<form action="{f:uri.action(action: 'search')}" method="get">
  <input type="text" name="q" />
</f:form>
```
or:
```
<f:link.action action="search" additionalParams="{q: 'preset-query'}">Link</f:link.action>
```
..if you want to set the query param directly.

**Comment by bwaidelich** [comment]
@johannessteu @Torsten85 @kitsunet do you agree? can we close this one?

**Comment by johannessteu** [comment]
Yes!

**Comment by mficzel** [comment]
Regarding this issue i wonder wether it would still help to configure wether a route/resolve should be cached and how long. 
Maybe we can add the foilowing settings to the routing configuration:

```yaml
routeCache: int|false (default 0)
resolveCache: int|false (default 0)
```

**Comment by bwaidelich** [comment]
> i wonder wether it would still help to configure wether a route/resolve should be cached and how long

@mficzel I'm a little skeptical about this approach because uncached routing is really slow:
As soon as the router hits an uncached route, _all_ routing configuration has to be merged and parsed and iterated etc.

Instead I would suggest that we try to tackle the _root_ cause of this confusion (#2901) and make it really easy to use a single route for all those "unbound" usecases. Those are what query parameters are for.

E.g. for the example above the following should be possible IMO:

```html
<f:link.action action="search" queryParameters="{q: 'preset-query'}">Link</f:link.action>
```

or, with Fusion:

```
url = Neos.Fusion:ActionUri {
  action = 'search'
  queryParameters.q = 'preset-query'
}
```

**Comment by bwaidelich** [comment]
> allow to set a cache lifetime

My concerns would still apply and I wonder about the usecase for this? Maybe I'm wrong but if you create cache entries from "unbound" values (i.e. external sources) cache flooding could be an issue with or without a shorter lifetime

**Comment by mficzel** [comment]
> My concerns would still apply and I wonder about the usecase for this? Maybe I'm wrong but if you create cache entries from "unbound" values (i.e. external sources) cache flooding could be an issue with or without a shorter lifetime

Yes but one could limit the impact, and could also adjust this per route.

**Comment by bwaidelich** [comment]
> Yes but one could limit the impact, and could also adjust this per route

I still think that this would just tackle the symptoms and IMO a global cache lifetime would achieve almost the same. But I won't block this of course if others think otherwise.

> Thinking about that one route that really needs appendExceedingArguments for whatever reason

To be honest, I'm questioning the `appendExceedingArguments` feature itself..
When I came up with it, it made sense to me that a route can control whether an argument is mapped to part of the URI path or query parameters. But it's confusing and easily used "incorrectly".

Probably we would have been better off, leaving query parameters _completely_ out of the routing game.

Getting rid of it now wouldn't be an easy task though...
