### ISSUE TITLE
Form validation, multiple forms, same properties, different objects, fails to display properly

### ISSUE THREAD

**Issue by kaystrobach** [neos/flow-development-collection#1570]
### Description

given you have three forms like this on a single page, once you submit that form you get a form error for that field, now the error is displayed for all forms on that page matching the property. Also the false inserted property is displayed in all three forms. That means, that flow can not decide which form on a page has send the data - any idea how to fix that? I do currently think about a Data Transfer Object, but i would love to see a general bugfix for that.

```
html
<f:form action="update" objectName="object" object="{pruefung}" name="">
    <custom:form.numberTextfield property="notenwert" decimalSeparator="," thousandsSeparator="." decimals="1" class="form-control"/>
</f:form>
```

### Steps to Reproduce

1. create 3 forms, e.g. for accounts on a single page
2. enter invalid data
3. all 3 forms show the error, even if just one has produced it.

#### Expected behavior

the sending form highlights the failing fields via `error-css-class`

#### Actual behavior

all fields with the same name get the error-class applied

### Affected Versions

Flow: starting from 2.x to 5.x

![grafik](https://user-images.githubusercontent.com/1185776/57244222-3e775c00-7038-11e9-8189-805374e8f74c.png)

**Comment by albe** [comment]
Well, basically, that's what you are supposed to provide via the form object name, which is either one of "objectName" or "name" attribute. This will be used to build a unique path for this single form properties, which will map to an action argument. I do understand the use case here is, that you have the same form for different object instances displayed together, but you always only send one of them. Then on redisplay this happens, because all forms have the same objectName and same properties.

The thing here is, that the property mapper and validation framework only receive the property path+values and hence the Form ViewHelper can only find matching errors by this path. We could maybe somehow embed the object identifier of the parent object into the ValidationError path (would be breaking), but this would then still not work for objects that have not yet been persisted and have no client generated IDs.

Now the ID can not only depend on displayed properties or even properties+values, because I assume all three forms display the same properties and might in theory even have the same values - the only distinguishing thing is the object identities (which might not yet exist). So we need a true random unique ID, but here comes the problem: unless this ID can be deterministically be regenerated for the same form on re-render, we win nothing, because the round-tripped ID does not help us tell which form it belonged to originally, so we again end up with all forms either displaying the same, or none displaying the submitted values and errors. The only input we have for calculating the ID deterministically is: The object name, property names and values. So we've come full circle.

Here is the only solution I see: You need to deterministically assign a form-ID to the form at render time, so basically something like:
```html
<form id="0" objectName="object" ...></form>
<form id="1" objectName="object" ...></form>
<form id="2" objectName="object" ...></form>
```

See already where I'm getting at? You can just embed this id into the objectName (or rather property names, because you map to a single action and this only receives a single argument name - you could also just receive three different objectNames in the action and make them all optional, but meh) and basically wrap your submitted object into a DTO with a deterministic key for each instance of your object.

```html
<form objectName="objectDto" ...><input property="0.myField" ... /></form>
<form objectName="objectDto" ...><input property="1.myField" .. /></form>
...
```

And your DTO becomes a map of `key => form object` that basically looks like:
```php
class MyFormDto {
    /**
     * @var array<MyFormObject>
     */
    protected $object;
}
```
Which your action receives and happily just takes the single (first) element in the array to do it's actual stuff. This might look strange, but what you basically built is **a multi object submit form that always only receives a single object in the first place**.
You could achieve the same with a single form that sends this DTO and just work on all three (or whatever many) object instances together - the ones that are unchanged will be optimized away through persistence dirty check anyway, or you manage that yourself with a client side flag/key sent through each of the three submit buttons.

Sorry for the long elaboration, but I was already deep into trying to pass some kind of new magic internal argument through the whole Framework and back until I noticed the obvious: that it will just not work out. Then deleted only half of my writing.
I hope that helps understand the issue, and let me know if I'm missing something :)

**Comment by kaystrobach** [comment]
Thank you for the explanation. I do understand the problem technically. 

I thought about using the id field of the form for calculating the failing props - which can be assigned as via an interation index etc. Anyway it would be breaking.

The option via an DTO is what we also discussed internally. But this breaks validation group usage (save only values which are not null and some other constraints).

**Comment by albe** [comment]
> But this breaks validation group usage (save only values which are not null and some other constraints).

Care to explain that part in more depth? I don't think I see how this would break - but if, maybe that's the thing to fix?

**Comment by kaystrobach** [comment]
Sure, we have a Model, which normally allows you to save float and null value to a property called `x`.

In that special cae, we wan`t to make sure, that the float ends either with `.5` or `.0`, so we added a validationgroup for that, to ensure, that only this kind of values is saved.

Also the saving of such a value triggers some workflows which are then executed.

Maybe we can solve that by ignoring null values in our validator.

**Comment by albe** [comment]
> so we added a validationgroup for that, to ensure, that only this kind of values is saved.

That's an interesting use-case for validationGroup! Can you share a little bit of how you set that up? I would have just gone with an own Validator class for that, e.g. `MultipleOfOneHalfValidator` and that'd be it, but I guess I'm missing something here.

> Maybe we can solve that by ignoring null values in our validator.

This could be a solution maybe. But I haven't fully grasped the issue yet I think :)

**Comment by kaystrobach** [comment]
```php
class NotenValidator extends \Neos\Flow\Validation\Validator\AbstractValidator
{

    /**
     * Check if $value is valid. If it is not valid, needs to add an error
     * to Result.
     *
     * use it like (remove space after @ ...):
     *
     * <code>
     *  @ Flow\Validate(argumentName="student", type="SBS.LaPo:Student\Noten")
     * </code>
     *
     * @param mixed $value
     * @return void
     * @throws \Neos\Flow\Validation\Exception\InvalidValidationOptionsException if invalid validation options have been specified in the constructor
     */
    protected function isValid($value)
    {
        $flooredValue = (int)$value;
        $partAfterKoma = $value - $flooredValue;
        if (($partAfterKoma != 0) && ($partAfterKoma !== 0.5)) {
            $this->addError('grade can only be .0 or .5 after the comma', 1433078772);
        }
    }
}
```

And then we use additional code in the controller to init the related workflow.

**Comment by kaystrobach** [comment]
For displaying the errors near the field we use code like this:

```html
<f:if condition="{property}">
    <f:validation.results for="{bs:form.fieldNamePrefix(fieldName: property)}">
        <f:if condition="{validationResults.flattenedErrors}">
            <span class="help-block">
                <ul class="list-unstyled">
                    <f:for each="{validationResults.flattenedErrors}" as="errors" key="property">
                        <f:for each="{errors}" as="error">
                            <li>
                                <f:if condition="{f:translate(id:error.code, source:'Main', arguments:error.arguments)} == {error.code}">
                                    <f:then>
                                        <f:translate id="{error.code}" package="Neos.Flow" source="ValidationErrors" arguments="{error.arguments}"></f:translate>
                                    </f:then>
                                    <f:else>
                                        <f:translate id="{error.code}" source="Main" arguments="{error.arguments}">{error.code}</f:translate>
                                    </f:else>
                                </f:if>
                                <span class="glyphicon glyphicon-info-sign" title="{error.severity} {error.code}: {error}"></span>
                            </li>
                        </f:for>
                    </f:for>
                </ul>
            </span>
        </f:if>
    </f:validation.results>
</f:if>
```

with the following VH to ensure we get the right fieldnamePrefix

```php
<?php

namespace KayStrobach\Bootstrap\ViewHelpers\Form;

use Neos\FluidAdaptor\Core\ViewHelper\AbstractViewHelper;
use Neos\FluidAdaptor\ViewHelpers\FormViewHelper;
use Neos\Flow\Annotations as Flow;

class FieldNamePrefixViewHelper extends AbstractViewHelper
{
    public function render($fieldName = '')
    {
        if ($fieldName === null || $fieldName === '') {
            return '';
        }
        if (!$this->viewHelperVariableContainer->exists(FormViewHelper::class, 'formObjectName')) {
            return $fieldName;
        }
        $fieldNamePrefix = (string)$this->viewHelperVariableContainer->get(FormViewHelper::class, 'formObjectName');
        if ($fieldNamePrefix === '') {
            return $fieldName;
        }
        return $fieldNamePrefix . '.' . $fieldName;
    }
}
```

**Comment by kaystrobach** [comment]
That would atleast allow us to fetch the argument with a number as prefix on the `objectName` from the form, but that feels weird and wrong to implement in the controller ... .

**Comment by albe** [comment]
```php
$partAfterKoma = $value - $flooredValue;
if (($partAfterKoma != 0) && ($partAfterKoma !== 0.5)) {
```
Be aware that this might suffer from float precision issues. Generally avoid comparing to exact float values. The more robust way to check this would be to do s.th. like
```php
$decimalPart = round(($value - $flooredValue) * 10) % 10;
if ($decimalPart !== 0 && $decimalPart !== 5) {
```

Anyway, back to the original issue: I don't yet see where the ValidationGroup comes into play, but from what I see, I would indeed solve it by going the way I suggested in my long text:

```html
<form objectName="objectDto" ...><input property="0.myField" ... /></form>
<form objectName="objectDto" ...><input property="1.myField" .. /></form>
...
```
or with a loop
```html
<f:for each="{allFormObjects}" as="formObject" key="index">
   <f:form objectName="objectDto" object="{allFormObjects}" ...>
       <f:form.textfield property="{index}.myField" ... />
       <f:validation.results for="objectDto.{index}.myField">
           ...
       </f:validation.results>
   </form>
</f:for>
```

What I do like though, is the concept of getting the "scope" of the validation.results VH from a possibly existing parent `<f:form>` like in `FieldNamePrefixViewHelper`. This would make it much more straightforward to get matching validation results inside the form.

The example above could then look like, which is much more obvious:
```html
<f:for each="{allFormObjects}" as="formObject" key="index">
   <f:form objectName="objectDto" object="{allFormObjects}" ...>
       <f:form.textfield property="{index}.myField" ... />
       <f:validation.results for="{index}.myField">
               ...
       </f:validation.results>
   </form>
</f:for>
```
So I'm open for getting this into core, it could even be done fully backwards compatible by checking if the form object name is still specified in the `for` argument.

And a next thing to improve, would be to allow a path inside the `objectName` property of the form, because then you could also get rid of all that `"{index}.` crap and the form would look much cleaner:
```html
<f:for each="{allFormObjects}" as="formObject" key="index">
   <f:form objectName="objectDto.{index}" object="{formObject}" ...>
       <f:form.textfield property="myField" ... />
       <f:validation.results for="myField">
               ...
       </f:validation.results>
   </form>
</f:for>
```
Notice how we now bind the form to the actual single formObject instead of the full list, which is so much more straightforward. That would need a bit of adjustment inside the `AbstractFormFieldViewHelper` though and possibly be breaking, but still worth it IMO.

**Comment by albe** [comment]
@kaystrobach are you okay with closing this in favor of the actionable suggestions made in #1585 ? Would those solve your issue sufficiently?

**Comment by kaystrobach** [comment]
i think so, still would expect, that we can simply supply some kind of form id (maybe the object identifier), to bind forms predictable, if no identifier is bound, the object might be used to "guess" the identifier
