### ISSUE TITLE
Rework travis setup to use build stages instead of build matrix

### ISSUE THREAD

**Issue by albe** [neos/flow-development-collection#1659]
Build Stages allow to define dependent and parallel jobs (https://docs.travis-ci.com/user/build-stages/) and a failing stage prevents all following stages from running.

This could be used to optimize our travis builds, e.g. by having a first stage "code quality" that does some static analysis checks (see #1658), then unit tests and only then run the costly functional tests.

**Comment by albe** [comment]
@kdambekalns I'd specifically like your input on this

**Comment by kdambekalns** [comment]
TBH I don't really understand how stages and build matrix interact. We need the build matrix for the PHP/DB versions, so that needs to stay for the tests. From a quick look at the docs it seems as if these are not really integrated concepts.

And we do run functional tests only if the unit tests fail, so… 

Do you know more about the details, @albe?

**Comment by albe** [comment]
From what I read, they somehow interact with each other in the sense that a matrix is basically the underlying concept and build stages are an abstraction on top. I might be wrong though, I just barely flew over the docs till now and it sounded useful. I'll invest a bit more time to read into this.

> And we do run functional tests only if the unit tests fail, so…

How that? AFAIS functional tests are just run after the unit tests all the time, or does jenkins skip following scripts if one fails? Haven't seen that being the case, but again I might be wrong.

**Comment by albe** [comment]
Closing this, since with #2273 this will be obsolete (or easily achievable via the matrix).
