### ISSUE TITLE
Session cookies should set sameSite attribute

### ISSUE THREAD

**Issue by kdambekalns** [neos/flow-development-collection#2031]
### Description

To avoid problems in the future the session cookies should set the sameSite attribute.

### Steps to Reproduce

1. Open browser console
2. Use a Flow site using sessions, e.g. the Neos UI

#### Actual behavior

`Cookie “Neos_Session” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite`

https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by albe** [comment]
Related to https://github.com/neos/flow-development-collection/pull/1948

**Comment by kdambekalns** [comment]
Doh! So we have this already? How could I not know? 😬

Can we supply a (sane) default then? Or at least add documentation around this?

**Comment by albe** [comment]
👍 for better default, if the current default (not setting it) causes issues. If I read the message correctly, it states that since we don't set `sameSite` ("invalid value"?) we need to set `secure` - so maybe this line here needs to be changed: https://github.com/neos/flow-development-collection/pull/1948/files#diff-f54a6ca136b1699030b162872fe3be26R155 to include `|| $sameSite === null`?

And I really thought there was a documentation segment, but it seems there isn't :/ Need to be better with checking this before merging in the future

**Comment by kdambekalns** [comment]
Well, `seecure` makes the cookie unavailable in a non-TLS context. In production this should not be an issue, but probably a lot of development setups miss encryption. Turning secure on based on `sameSite` seeems wrong, those are only very slightly related (even the alrady merged change is a bit too much magic IMHO). I'd rather turn secure on if encryption is detected, but even that would probably be too much.

A different default value OTOH is something that's fine with me.

**Comment by sorenmalling** [comment]
The setting `secure` is "dependent" on the request object at hand, right?

**Comment by albe** [comment]
So coming back to the "better default" : would that be "strict" or "lax"? "none" is out of the question, since it (currently) imposes "secure" as well.

**Comment by kdambekalns** [comment]
Seeing that `Lax` is the default in browsers, we could use that, too.
