### ISSUE TITLE
Neos.Flow: InstallerScripts class for composer is not compatible with composer 2

### ISSUE THREAD

**Issue by robert-heinig** [neos/flow-development-collection#2120]
In
https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/composer.json
there is a dependency to `"composer/composer": "^1.9"` but composer did not complain while upgrading a Neos 5.2 to 5.3 with composer 2 RC1.

In 
https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Composer/InstallerScripts.php
wihtin the method `postPackageUpdateAndInstall()` the call `$operation->getJobType()` is used 4 times.
This method `getJobType` was renamed to `getOperationType` within composer 2:
https://github.com/composer/composer/commit/5bdc0fc9c5cc107d889dbbce30e2e4483673f2c5#diff-fbab13faf7a9485e442e629e12f0f31a

With the composer dependency to ^1.9 not seeming to work properly I'm not sure how to solve this issue correctly.
A check with method_exists() is a possibility, but that seems not to be a nice solution.

Within my Neos project I'm using `cweagans/composer-patches` and a composer patch file that renames the method.

**Comment by albe** [comment]
Thanks for bringing this up! Since we're likely to have to support composer 1.x & 2.x for some time and the installer scripts is basically glue code between the infrastructure software and us, something like the method_exists() check is probably okay.

So if anyone is willing to play around, feel free to start a PR!

See https://github.com/composer/composer/issues/8726
https://github.com/composer/composer/blob/master/UPGRADE-2.0.md#for-integrators-and-plugin-authors

**Comment by kdambekalns** [comment]
Fixed with latest release(s), see also #2187
