### ISSUE TITLE
allowObject($object) commented out in PersistenceManagerInterface

### ISSUE THREAD

**Issue by lsascha** [neos/flow-development-collection#2398]
### Description

I updated from neos/flow version 6.1.3 to 6.1.13 and noticed that whitelistObject($object)
in the PersitenceManagerInterface is now deprecated and i should use allowObject instead. So i changed all occurences to allowObject.

However when i ran phpstan and psalm, it complained for `Call to an undefined method Neos\Flow\Persistence\PersistenceManagerInterface::allowObject()` 

So i looked and found that the method is commented out in the PersitenceManagerInterface but not in the AbstractPersistenceManager implementing the PersistenceManagerInterface.

### Steps to Reproduce

1. change $this->persistenceManager->whitelistObject($object) usage to $this->persistenceManager->allowObject()
2. Run phpstan or psalm

#### Expected behavior

No errors in psalm or phpstan when using the non-deprecated method.

#### Actual behavior

errors in phpstan or psalm that allowObject() is undefined

### Affected Versions

Flow: version 6.1.7 up to 7.0.2 and master.

**Comment by albe** [comment]
Well, that is correct, because adding the method to the Interface would have been a breaking change. So we added it but out-commented it. We should have added it to the interface (and removed `whitelistObject()`) in 7.0 though soooo... :grimacing: well, I'll add a reminder for next major. ☑️ 
Until then it is technically okay to use either one of the methods but any static analysis tool will complain about `allowObject()`. You can either tell the tool to ignore this occurence or switch back to `whitelistObject()` until next major.

Hope that helps clear that up :)

**Comment by lsascha** [comment]
No problem. I already ignored it in the static analysis tools. :) I just thought it might have been an oversight
