### ISSUE TITLE
UriConstraints should make sure the Uri path starts with a slash

### ISSUE THREAD

**Issue by albe** [neos/flow-development-collection#2473]
See https://github.com/guzzle/psr7/blob/1.4.1/src/Uri.php#L704

**Comment by albe** [comment]
Related to #2501 and #2502

**Comment by arsors** [comment]
I also have a problem with "withPathPrefix()" in my package.

Since psr7 requires the path to start with a "/" [this query](https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Mvc/Routing/Dto/UriConstraints.php#L261) should be exactly the opposite. 
Currently it checks if there is a "/" at the beginning and then gives an error. In my opinion it should rather check if there is no "/" at the beginning and then give an error.

In the core "withPathPrefix()" is currently only used in one place. I just don't know what effect it has on [this line](https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Mvc/Routing/Router.php#L200).

**Comment by albe** [comment]
Linking in @bwaidelich since he is the most involved in that part of the code base. From my limited PoV that sounds reasonable, though I'm unsure what subtle consequences would come from turning around that method's expectations.

Also note, that we already enforce a `/` prefix on the final URI in https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Mvc/Routing/Dto/UriConstraints.php#L396
Plus we have this check here, that might also need to be changed to be consistent: https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Mvc/Routing/Dto/ResolveContext.php#L74 (and make `ResolveContext::getUriPathPrefix()` work with `UriConstraint::withPathPrefix()` in the Router as mentioned above).
Most notably, probably this here needs to change to accomodate joining prefixes with a leading `/` and a trailing `/` correctly: https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Mvc/Routing/Dto/UriConstraints.php#L258

Also should we still allow `''` as uriPathPrefix (for b/c) and translate it to `'/'`? IMO would make sense, but maybe there's an edge case where this would hide a subtle bug (e.g. a stringification of something that should not be empty).

**Comment by bwaidelich** [comment]
Sorry for the late reaction, I lost track of this one.
IIRC we expect paths _not_ to start with `/` _internally_ for historic reasons (i.e. the routePath will always be without leading slash).
Couldn't we just fix the two `new Uri('')` calls in `UriConstraints` (https://github.com/neos/flow-development-collection/blob/68321067e83dc82702d266f6b27b4f4afad54186/Neos.Flow/Classes/Mvc/Routing/Dto/UriConstraints.php#L282 and https://github.com/neos/flow-development-collection/blob/68321067e83dc82702d266f6b27b4f4afad54186/Neos.Flow/Classes/Mvc/Routing/Dto/UriConstraints.php#L423) instead of changing the whole behavior (and potentially introducing breaking changes)?

**Comment by kdambekalns** [comment]
> Couldn't we just fix the two `new Uri('')` calls in `UriConstraints`

That needs at least some more adjustments:

```
There were 3 failures:

1) Neos\Flow\Tests\Unit\Mvc\Routing\Dto\UriConstraintsTest::applyToTests with data set #54 (array('query'), 'http://some-domain.tld/some/path/', false, '/some/path?query')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'/some/path?query'
+'/some/path/?query'

/Users/karsten/Sites/neosdev/Packages/Framework/Neos.Flow/Tests/Unit/Mvc/Routing/Dto/UriConstraintsTest.php:119

2) Neos\Flow\Tests\Unit\Mvc\Routing\Dto\UriConstraintsTest::applyToTests with data set #57 (array('frägment'), 'http://some-domain.tld/some/path', false, '/some/path#fr%C3%A4gment')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'/some/path#fr%C3%A4gment'
+'/some/path/#fr%C3%A4gment'

/…/Framework/Neos.Flow/Tests/Unit/Mvc/Routing/Dto/UriConstraintsTest.php:119

3) Neos\Flow\Tests\Unit\Mvc\Routing\Dto\UriConstraintsTest::applyToTests with data set #58 (array('fragment'), 'http://some-domain.tld/some/p...laceme', false, '/some/path#fragment')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'/some/path#fragment'
+'/some/path/#fragment'

/…/Framework/Neos.Flow/Tests/Unit/Mvc/Routing/Dto/UriConstraintsTest.php:119
```

**Comment by kdambekalns** [comment]
That seems to work, if we are to trust our tests…
