### ISSUE TITLE
The result of MethodRefelection::getTagValues() changed from Neos 7.1 to Neos 7.2

### ISSUE THREAD

**Issue by daniellienert** [neos/flow-development-collection#2612]
This leads in my case to the problem, that frontend forms are not submittable if an active backend session is present. It leads to a `#1486500872: The action could not be executed because you supplied no or the wrong CSRF protection token´

@bwaidelich on Slack

> The reason seems to be that $this->reflectionService->isMethodTaggedWith($controllerClassName, $actionMethodName, 'skipcsrfprotection') (https://github.com/neos/flow-development-collection/blob/a4c625d558d6acabb9ed58a3fdb7559ab0bbda74/Neos.Flow/Classes/Security/RequestPattern/CsrfProtection.php#L110)
> no longer returns true for the \Neos\Neos\Controller\Frontend\NodeController::showAction method (that is annotated with @Flow\SkipCsrfProtection).
> The ReflectionService returns flow\skipcsrfprotection as tag instead of just skipcsrfprotection – so I assume that this is related to the recent changes to the annotation parsing that came with the PHP 8 compatibility /cc @a.berl
> 

The result of MethodRefelection::getTagValues() in Neos 7.1 and Neos 7.2:

Neos 7.1:

```
Neos\Flow\Reflection\ReflectionService::isMethodTaggedWith:763
array(5)
 'param' (5) => array(1)
   integer 0 => 'NodeInterface $node' (19)
 'return' (6) => array(1)
   integer 0 => 'string View output for the specified node' (41)
 'throws' (6) => array(1)
   integer 0 => 'NodeNotFoundException | UnresolvableShortcutException | NeosException' (69)
 'skipcsrfprotection' (18) => array(empty)
 'ignorevalidation' (16) => array(1)
   integer 0 => 'argumentName="node' (18)
```

Neos 7.2:
```
Neos\Flow\Reflection\ReflectionService::isMethodTaggedWith:769
array(5)
 'param' (5) => array(1)
   integer 0 => 'NodeInterface $node' (19)
 'return' (6) => array(1)
   integer 0 => 'string View output for the specified node' (41)
 'throws' (6) => array(1)
   integer 0 => 'NodeNotFoundException | UnresolvableShortcutException | NeosException' (69)
 'flow\skipcsrfprotection' (23) => array(1)
   integer 0 => 'We need to skip CSRF protection here because this action could be called with unsafe requests from widgets or plugins that are rendered on the node - For those the CSRF token is validated on the sub-request, so it is safe to be skipped here' (240)
 'ignorevalidation' (16) => array(1)
   integer 0 => 'node' (4)
```

Related changes in Neos 7.2:
- https://github.com/neos/flow-development-collection/pull/2404

**Comment by albe** [comment]
The pinning was only to make sure that the NamedArgumentsConstructor tag is available for the PHP8 attribute changes of our existing annotations. Yes, before the pinning it would just install whatever highest version would fit, which would make things fail for the lowest-dependencies tests. I doubt the annotations version is the issue though...

**Comment by sorenmalling** [comment]
I've written a test that confirms the issue, and digging might have broguht me to DocCommentParser::parseDocComment and the if condition

**Comment by kitsunet** [comment]
despite it being used that way I would still want to ask if this an actual usecase we even _should_ tackle, because again, I think this is an annotation not a tag so taggedWith should _technically_ IMHO not even return anyithng, that it does is more of a legacy thing.

**Comment by kitsunet** [comment]
I wasn't even aware it was used in this way, so I don't know. Will have a look. But yeah suggestion would be to note this behavior down, fix core and be happy, unless someone _knows_ a good usecase making this necessary.

**Comment by albe** [comment]
I agree it's a very odd use-case, but what really gets me is that the behaviour has seemingly changed between 7.1 and 7.2. After taking a little look now, I'm even more confused, because the part that parses tags (https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Reflection/DocCommentParser.php#L118-L122) did not change since a long time (the one change with the replace from https://github.com/neos/flow-development-collection/pull/1901 is not the cause). As far as I see, the regex there only matches annotations without comments (due to the `$` line-ending) since ever. So I do not see how `isMethodTaggedWith()` should have changed.
Also, the method that is reflected and has the dubious comment-after-annotation didn't change between 7.1 and 7.2: https://github.com/neos/neos-development-collection/blob/7.1/Neos.Neos/Classes/Controller/Frontend/NodeController.php#L100

That leaves me with only one possible explanation: Difference in PHP version and regex processing?

Anyway, the CsrfProtection class does indeed check for `isMethodTaggedWith(..., 'skipcsrfprotection')`, last changed 2011, so the expectation seems to always have been that an `@Flow\SkipCsrfProtection` annotation is roughly equivalent to `@skipcrsfprotection` from the reflection PoV (or maybe the implementation there was only adjusted to make it work under observed behaviour).

So how should we proceed? Change that to `isMethodAnnotatedWith()` and make annotations not parse as tags (without namespace) which is breakish, or keep the behaviour and fix it such that comments are allowed there (only needs the removal of the `$` from the regex).

**Comment by kitsunet** [comment]
I don't mind to find the source and fixing it in general, BUT see this old change that introdcued annotatedWith. It WAS actually changed in the Csrf aspect but I guess falsely reintroduced into the CsrfProtection pattern later.

**Comment by albe** [comment]
> I don't mind to find the source and fixing it in general, BUT see this old change that introdcued annotatedWith: [ba1f5fb#diff-7ddcae218dfcb4714bc5e9555513755606ee0bf47d01a5938ce2c2316221d714R77](https://github.com/neos/flow-development-collection/commit/ba1f5fb2adc2a274ce230c2d8328735f7d4e0e8b#diff-7ddcae218dfcb4714bc5e9555513755606ee0bf47d01a5938ce2c2316221d714R77)
> 
> It WAS actually changed in the Csrf aspect but I guess falsely reintroduced into the CsrfProtection pattern later.

Oh, that's interesting and shows that the current thing is actually a bug and not expected behaviour. So the only question then is if `isMethodTaggedWith` should *not* return annotations `@Acme\Foo` any more.

**Comment by kitsunet** [comment]
I guess I would at least wish to deprecate that and point out that it's a mistakenly leftover thing. We might want to consult @kdambekalns as well maybe. In the end it seems unreliable because of the naming alone as you already mentioned.

**Comment by kdambekalns** [comment]
Doh. Ask me, of all people? Why? 😎

I read through the comments here, and think we should do as suggested by @kitsunet – document clearly and fix our own usage.

---

Optionally don't return any _annotations_ when looking for _tags_ – even though that might open a can of worms. We could as well leave it as is. Let's see…

I changed `parseTags()` to behave as it does now, in https://github.com/neos/flow-development-collection/commit/0284ce6762f5bf54125ad9211895a8416b763872 and wondering why I tried out https://3v4l.org/sdXka#v7.4.25 and can conclude: the goal was to support `@something` and `@something(else)`, hence the `preg_match`. That does strip the "Flow prefix", making it a edge-casey thing.

Having `@something utterly different` is handled like "classic" tags (think `@param string $foo not a bar in sight`), and that case kicks in if there is anything but a parenthesized expression after the "tag", see https://regex101.com/r/DkVY2D/1

So, we should define what we want here for those cases, before touching that part…

- `@something`
- `@something and something else`
- `@foo\something`
- `@foo\something(bar)`
- `@foo\something(bar) a comment for sure`
- `@foo\something another comment for sure`

**Comment by albe** [comment]
Interesting again - so in the beginning, there were only tags `@AfterReturning`, `@Entity` etc. and those were changed to namespaced Annotations
https://github.com/neos/flow-development-collection/commit/0284ce6762f5bf54125ad9211895a8416b763872#diff-9d723413f2d12c5600795b39ff2e26551bc1e91d4aa438edcc0a4f15e304b56dR43-R44
So for b/c the parser trimmed the namespace and handled the annotations as if they were still tags, which makes sense.
But I'm curious why only https://github.com/neos/flow-development-collection/commit/0284ce6762f5bf54125ad9211895a8416b763872#diff-7ddcae218dfcb4714bc5e9555513755606ee0bf47d01a5938ce2c2316221d714R76 wasn't changed to `isMethodAnnotatedWith`

> So, we should define what we want here for those cases, before touching that part…
> 
> @something
> @something and something else
> @foo\something
> @foo\something(bar)
> @foo\something(bar) a comment for sure
> @foo\something another comment for sure

If you ask me, either we parse all of those such that they only return the `@X\Y` part as tags, or we only allow `@something` and `@something and something else` (both returning `something` as tag).

**Comment by kitsunet** [comment]
For me that is part of the distinction of tag vs annotation (at least in my head), a tag is something passive, like tagging on social media, it has no attributes no nothing `@foobar` and everything after is a comment, while annotations are more "active" constructs that can have properties / attributes. 
I asked myself the same thing @albe about that commit but I concurred that development happened in parallel and either the commit dates do not correctly reflect how it was ultimately merged or it was simply overlooked, I doubt it was intentionally left.
I personally would prefer to say this behavior is fully deprecated and in the future annotations are no longer accessible in any form as tags, but if we wanted I would say strip all arguments and lowercase everything, so `@Foo\Bar(attribute="value")` would become the `foo\bar` tag.

**Comment by albe** [comment]
> The result of MethodRefelection::getTagValues() in Neos 7.1 and Neos 7.2:

Just tried to reproduce the difference between 7.1 and 7.2 and I can't see it (as expected from no changes in the relevant code). In both cases:
```
@Flow\SkipCsrfProtection Some comment
array(1) {
  ["flow\skipcsrfprotection"]=>
  array(1) {
    [0]=>
    string(12) "Some comment"
  }
}

@Flow\SkipCsrfProtection
array(1) {
  ["skipcsrfprotection"]=>
  array(0) {
  }
}
```
Maybe @daniellienert can confirm?

**Comment by kdambekalns** [comment]
The difference is not in the function behavior, but in the comment we added to that annotation that is now handled incorrectly.

**Comment by kdambekalns** [comment]
**Now I get it!** The comment has been there for years, so that cannot be the reason, right? Well, since we copy the docblocks instead of writing them (see https://github.com/neos/flow-development-collection/pull/2533), the comment appears in the reflected proxy class! Heureka!

**Comment by bwaidelich** [comment]
Great finding. Let's move that comment to a separate line as hotfix and switch to proper annotations in the `CsrfProtection` with the next version. WDYT?

**Comment by kdambekalns** [comment]
Following a call with @daniellienert, @albe and @robertlemke this is what I suggest.

This lists the input with current result and expected/correct result. Input marked with ✅ is handled fine already, the handling of input marked ❌ needs to be fixed.

- `@something` ✅
  - `['something' => []]`
  - `['something' => []]`
- `@something and something else` ✅
  - `['something' => ['and something else']]`
  - `['something' => ['and something else']]`
- `@foo\something` ❌
  - `['something' => []]`
  - `['foo\something' => []]`
- `@foo\something(bar)` ❌
  - `['something' => ['bar']]`
  -  `['foo\something' => ['bar']]`
- `@foo\something(bar) a comment` ❌
  - `['foo\something(bar)' => 'a comment']`
  - `['foo\something' => ['bar']]`
- `@foo\something and something else` ✅
  - `['foo\something' => 'and something else']`
  - `['foo\something' => 'and something else']`

With this, the behaviour of the method depends solely on parentheses being present or not:

- if parentheses follow the taga/annotation, whatever is in them will be the "value" of the "tag", anything following is treated as a comment and discarded
- otherwise whatever is after the "tag" becomes the "value"

That way the method can be used for "annotations" (potentially having options in parentheses) and "tags" (as in `@param or '@return`), keeping the breakiness low, as far as possible.

**Keep in mind, that for annotations the better suited methods should be used, like `isAnnotatedWith(…)`**

---

That needs to be implemented and we should fix our use of that method, too (as in https://github.com/neos/flow-development-collection/commit/ba1f5fb2adc2a274ce230c2d8328735f7d4e0e8b#diff-7ddcae218dfcb4714bc5e9555513755606ee0bf47d01a5938ce2c2316221d714R77.)

Do you agree to the expected behaviour outlined above?

**Comment by bwaidelich** [comment]
> Do you agree to the expected behaviour outlined above?

Yes, makes a lot of sense to me. Thanks for writing this up!

**Comment by kitsunet** [comment]
I find this conditional deciding a bit awkward, but sure, that would definitely work

**Comment by albe** [comment]
> @foo\something(bar) a comment
> ['foo\something(bar)' => 'a comment']
> ['foo\something' => ['bar']]

My first intuition was ['foo\something' => ['bar', 'a comment']], but I do see how ignoring the comment after a parathesized argument string could be plausible. Just feels weird to have "content" conditionally stripped off in something as simple as "parse this docblock line for a tag".

Question to make sure:

> `@foo\something(bar="foo", baz=100, quux=false) a comment`

would be what then?

> ['foo\something' => ['bar="foo"', 'baz=100', 'quux=false']]

or

> ['foo\something' => ['bar="foo", baz=100, quux=false', /* 'a comment' */]]

**Comment by bwaidelich** [comment]
> My first intuition was ['foo\something' => ['bar', 'a comment']]

But that wouldn't be distinguishable from `@foo\something(bar, a comment)` I assume?

> feels weird to have "content" conditionally stripped off in something as simple as "parse this docblock line for a tag".

If we would strip the substring from the doc comment result, that would be weird indeed. But I think it's perfectly fine to assume that the tag ends with the closing parenthesis.

> @foo\something(bar="foo", baz=100, quux=false) a comment

I think that should result in

`['foo\something' => ['bar => 'foo', 'baz' => '100', 'quux' => 'false']]`

or is that completely off the current implementation?

**Comment by kdambekalns** [comment]
I updated  https://github.com/neos/flow-development-collection/issues/2612#issuecomment-963088374 with the examples from https://github.com/neos/flow-development-collection/issues/2612#issuecomment-963283264

**Comment by kdambekalns** [comment]
To be clear, this method does not care about what the "value" is. Put into a "picture":

<img width="558" alt="image" src="https://user-images.githubusercontent.com/95873/140779235-ce6085a4-c6d1-4ad9-9373-a3121a5bcfcf.png">

**Comment by kitsunet** [comment]
> To be clear, this method does not care about what the "value" is. Put into a "picture":
> 
> <img alt="image" width="558" src="https://user-images.githubusercontent.com/95873/140779235-ce6085a4-c6d1-4ad9-9373-a3121a5bcfcf.png">

I still find case 2 vs. 5 and 8 a bit weird as @bwaidelich said as well. it seems smelly that this syntax is treated so differently but I guess that's how it has to be...  I still think we should ignore everything that is a proper annotation and basically just treat the first two cases of that screenshot as tag. The rest is not taggedWith(), but annotatedWith IMHO, but I am fine proceeding as lined out in the cases above if that'S what we agree on.

**Comment by albe** [comment]
Will add the cases to the tests in #2615 tomorrow, then adjust the implementation based on that.

**Comment by runner78** [comment]
I noticed that PHP8 attributes are ignored for tags, so.B you can't use SkipCsrfProtection as an attribute and only as a PHPdoc annotation. Flow 7.2 seems to be very inconsistent here regarding PHP8 attributes.

**Comment by albe** [comment]
Yeah, that's exactly the thing this should solve as well - we used `isTaggedWith('skipcsrfprotection')` instead of `isAnnotatedWith(Flow\SkipCsrfProtection::class)` - the latter should also work when PHP8 Attribute is applied. Thanks for the reminder though! Maybe we should also do a quick check if any other annotations are checked as `isTaggedWith()` but on first glance I couldn't find anything else.

**Comment by runner78** [comment]
It is not linked directly to tags, but I also noticed that the proxy class for controller actions, parameter attributes are missing.

**Comment by Chxyz** [comment]
Hello,
As we can see above, a temporary fix has been merged in the 7.2 neos-development-collection branch. 
But what about the 7.3 (LTS)  branch?
Thank you for your help.

**Comment by bwaidelich** [comment]
> But what about the 7.3 (LTS) branch?

newer branches will be updated via [upmerge](https://discuss.neos.io/t/committers-guide-upmerging-guide/508) on a regular basis.
Usually the Release Managers take care of this. For 7.3 this would be @jonnitto , @sorenmalling and @markusguenther

**Comment by markusguenther** [comment]
Did I miss something... before the release I upmerged the branches :/

**Comment by bwaidelich** [comment]
Not sure but c58b22261d989ba2dfc2ff90d3207e1452060f9c seems to be only in 7.2

**Comment by markusguenther** [comment]
Checked that and I upmerged on the 6th of December. The commit from @daniellienert is from the 22nd of December. So, the commit was after the release. Since the release we had no upmerges if I don't get it wrong and the upmerge to master is also missing. Can take care tomorrow or later.

But that the commit is not part of 7.3 at the moment is correct.

**Comment by bwaidelich** [comment]
> But that the commit is not part of 7.3 at the moment is correct.

Great, thanks for checking!

**Comment by markusguenther** [comment]
Tried to up merge today, but now the pipeline is broken 🙈

**Comment by Chxyz** [comment]
Hello,
With the [Neos 7.3.1 release](https://github.com/neos/neos-development-collection/releases/tag/7.3.1) (containing the bugfix), I can confirm it's now working fine again.
Thank you!
