### ISSUE TITLE
Install mono repo via composer (dev collections)

### ISSUE THREAD

**Issue by mhsdesign** [neos/flow-development-collection#2831]
We currently have a custom package scan functionality, that looks in the Packages folder for flow packages. The idea is to replace this eventually by using the composer api (get all flow packages and done)

But we have some special behavior in place for monorepos like the dev collections. Currently in composers eyes they are just one package but to the flow package scan functionality the packages inside the collection will be seen as individuell single packages.

The idea is to find a way to install such dev collections natively via composer, so that when we ask the composer api for available packages it will return the packages from inside the collections too. So we can avoid implementating a custom functionality for this case.

i found this approach using path repos and this sounds good to me: https://medium.com/sroze/managing-monolithic-repositories-with-composers-path-repository-c28af031746d

**Comment by mhsdesign** [comment]
Uuups that was a 'schnapsidee' as the path repo of an installed 'vendor' package is not available at first...

**Comment by kitsunet** [comment]
yep, I think waht you describe is the way I would want to investigate as well. composer plugin to install the collections to $someTopLevelFolderToBeDefined then add that foldera as path repo and let composer core handle the rest.

**Comment by mhsdesign** [comment]
- And this would have the advantage that the collections behave like the `DistributionPackages` folder so one can easily add new packages to the collection.
- Also we dont need this composer manifest merge thingy for the dev collection.

I think this is really worth the effort and should simplify much for us.

**Comment by kitsunet** [comment]
From my POV sadly a close for now, had a look at symfony and a couple of other options to do this. None really does it like this and trying to get that running, it's certainly possible but has a bunch of problems. Ultimately you can setup yourself that way and manage the collection by hand, but you will have to manually version match the git repository and if you use a dev version require all packages as dev in root, seems pretty annoying and automating all that would be super tricky, because of how composer works. We could _probably_ wrap around the whole composer process but that would result in a globally installed alternative ultility I think which again isn't super helpful for using it on a broader scale.

**Comment by mhsdesign** [comment]
thanks for looking into it so deeply @kitsunet
