### ISSUE TITLE
Replace `self` with `static` in proxy classes

### ISSUE THREAD

**Issue by robertlemke** [neos/flow-development-collection#3059]
Factory methods may use code like `new self()` for creating a new instance. However, this code will break if the class is proxied, as `self` will still refer to the original class, which does not contain DI / AOP code. The compiler could therefore replace `self` keywords with `static` in the rendered proxy class file to work around this issue.

**Comment by mhsdesign** [comment]
Sweet

**Comment by bwaidelich** [comment]
as already commented on [Slack](https://neos-project.slack.com/archives/C050KKBEB/p1684399979909129?thread_ts=1684223801.762719&cid=C050KKBEB):

> rewriting `self` to `static` automagically seems dangerous to me due to the different semantics

I might be wrong on this one and I think we should definitely experiment with it to get to a stage were we can basically proxy any PHP class.

A safer alternative could be to rewrite (`private function __construct` to `protected function __construct`) (that would also fix the broken proxy class mentioned in #3060).

If everything turns out to be too flaky, I'd rather prevent those classes from being proxied at all.

**Comment by nezaniel** [comment]
I think this is the reason why I always have to add Proxy(false) to all my classes with static constructors; Might be a non-issue since they are probably no longer proxied anyway. Will test this thoroughly in the coming weeks

**Comment by mhsdesign** [comment]
Hi i just stumbled upon this (as i was searching, if i can use the `self` to `static` replacements and the `private` to `protected` rewrites now in neos 9 dev ^^).

Sorry for asking this, but im wondering if we should just disable proxy logic for `private` constructor classes?
Currently the proxy building seemed to got a bit more complex with the two prs #3074 and #3072. And possibly also slower as we now leverage `debug_backtrace` and `token_get_all`.

```php
class SomeService
{
   #[Flow\Inject]
   protected OtherService $otherThing;

   private function __construct() {}

   public static function create() { return new self(); }
}
```

i would argue this is hardly a usecase? (And i dont know if constructor injection should work, but i think there would be no reason for the developer that it _should_ work ^^ ...)

Currently most private constructors i see are in `readonly` models, where we need no proxy building. If im right, i think we have now the heuristic to do no proxy building here? https://github.com/neos/flow-development-collection/issues/3049 - so this `self` and `private` replace is only useful for services?

```php
// no proxy class?
final readonly class Dto
{
     private function __construct(public string $bar) {}

     public static function fromString(string $bar) { return new self($bar); }
}

// no proxy class? -> or maybe yes because of a non straight value?
final readonly class OtherDto
{
     private function __construct(public Dto $dto) {}

     public static function fromString(Dto $dto) { return new self($dto); }
}
```

**Comment by mhsdesign** [comment]
>. i would argue this is hardly a usecase? (And i dont know if constructor injection should work, but i think there would be no reason for the developer that it should work ^^ ...)

we discussed that we code like this might sometimes happen and as we already support it now we like to keep it

**Comment by bwaidelich** [comment]
> Sorry for asking this, but im wondering if we should just disable proxy logic for private constructor classes?

Previously I added `Flow\Proxy(false)` annotations to most of my classes. In the meantime I exclude object management for most classes via the `Neos.Flow.object.includeClasses` Setting or even move DTOs and classes I don't ever want to be AOPed to non-Flow packages..
Most of these issues arise because due to some regression a long time ago we create proxies for all classes.. see #3060
