### ISSUE TITLE
Adjust release scripts to keep `self.version` in manifests

### ISSUE THREAD

**Issue by kdambekalns** [neos/flow-development-collection#3186]
> Ah, the release scripts… I did not think of those. 🤦‍♂️

_Originally posted by @kdambekalns in https://github.com/neos/flow-development-collection/pull/3035#discussion_r1280384057_

**Comment by ahaeslich** [comment]
Staring down the rabbit hole and wondering how this will impact our next releases (especially the upcomming major). And I have questions 😇.

My observations and questions:

First of all: the releases published after #3035 was merged also changed the dependencies in `neos/eel`, `neos/fluid-adaptor` and `neos/kickstarter`.

While the removal of `self.version` happend inside `neos/flow` one package (`neos/utility-pdo`) was never marked as such in the first place. Was this intentional?

Looking into [neos-development-collection](https://github.com/neos/neos-development-collection) I can see the same changes comming up there since the release after introducing `self.version`. What is confusing is, that in many places we are using either the death star or a version constraint. Was the original intention for all packages maintained inside flow-development-collection or neos-development-collection to use `self.version` for dependency declaration between each other? Or should there be some exceptions?

**Comment by kitsunet** [comment]
I think we should do `self.version` for everything otherwise it probably doesn't belong in the collection in the first place, which might be the case for some of the utility packages. Pretty sure there is no _need_ to update utility-pdo but for now, I would say no exceptions, if it#s in the collection it gets self-version.

**Comment by kitsunet** [comment]
@kdambekalns looking at the scripts, I guess easiest would be to just scrap the whole `set-dependencies.sh` and change nothing in there? Or what was your plan...

**Comment by kdambekalns** [comment]
Well, I think we can get rid of anything that now sues `self.version`. If that leaves the script(s) empty, we can drop them, if not, they should at least be smaller.

**Comment by kdambekalns** [comment]
We solved this now, see

- https://github.com/neos/flow-development-distribution/pull/85
- https://github.com/neos/flow-development-collection/pull/3206
- https://github.com/neos/flow-development-collection/pull/3207
- https://github.com/neos/neos-development-distribution/pull/97
- https://github.com/neos/neos-development-collection/pull/4666

Thanks @kitsunet!
