### ISSUE TITLE
Translate VH can't translate strings with placeholders without defined id.

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#590]
Jira issue originally created by user @RafaelKa:

VH Translation won't work by original labels, which contain placeholders, if id is not set.

also following things won't work:

``` fluid
<f:translate value='Something "{0}" with "{1}"'/>
<f:translate>Something "{0}" with "{1}"</f:translate>
{f:translate(value: 'Something "{0}" with "{1}"'}
```

 Jira-URL: https://jira.neos.io/browse/FLOW-372

**Comment by albe** [comment]
Okay, I just checked this. The issue here simply is, that Fluid will parse the `{0}` placeholder into an empty value, so the Viewhelper will only get the `value` "Something with ." and hence the replacement of the placeholders can not take place. Not sure this can be solved from the Framework, especially with Standalone Fluid now. The solution would be to escape the placeholder with CDATA:

```
<f:translate value="Something with <![CDATA[{0}]]>." arguments="{0: 'foo'}" />
<f:translate><![CDATA[Something "{0}" with "{1}"]]></f:translate>
```
works flawlessly, however
```
{f:translate(value: '<![CDATA[Something "{0}" with "{1}"]]>')}
```
does not work, as it seems the inline style viewhelper syntax is not parsed correctly with the included CDATA.
Still, this is nothing we can solve here, so I'm closing this for now.
