### ISSUE TITLE
Documentation Update needed

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#621]
Jira issue originally created by user tpei:

Ever since version 2.0 Flow won't persist changes automatically, therefore the code snippet at
http://docs.typo3.org/flow/TYPO3FlowDocumentation/TheDefinitiveGuide/PartII/Controller.html
requires a
$this->persistenceManager->persistAll();
to be added to the indexAction of the SetupController

 Jira-URL: https://jira.neos.io/browse/FLOW-55

**Comment by RafaelKa** [comment]
I think small note with one sentence and refernce to ["Safe request methods are read-only"](http://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartIII/Persistence.html?highlight=persistall#safe-request-methods-are-read-only) on some place of "Create Action" section in [TheDefinitiveGuide/PartII/Controller.rst](http://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartII/Controller.html#create-action) is better.

Alternativelly this issue simply can be closed, because indexAction() is a safe one...

**Comment by sorenmalling** [comment]
The persisting is done only on POST, PUT, DELETE, PATCH as stated in the documentation

https://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartIII/Persistence.html?highlight=persistall#safe-request-methods-are-read-only

There is no persisting going on in the indexAction in the mentioned documentation (from original issue) so this issue will be closed :)
