### ISSUE TITLE
Rework HTTP implementation

### ISSUE THREAD

**Issue by bwaidelich** [neos/flow-development-collection#658]
The current HTTP stack is quite error prone and often leads to nasty bugs that are difficult to dissect.

Some problems I can think of atm:
### No difference between incoming and outgoing Request

We use the same `Http\Request` to create _outgoing_  requests (i.e. when interacting with the `Http\Clien\Browser`) as for processing _incoming_ requests.
This leads to a convoluted API
#### Request::createFromEnvironment()

The [official documentation suggests](http://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartIII/Http.html#creating-an-actionrequest) to use `Request::createFromEnvironment()` to fetch the current request, but this will obviously create a completely new instance which is not what we want in this case.
Note: #656 addresses this issue
#### Bootstrap::getActiveRequestHandler

That's the method that the Flow core uses in several parts (`Logger`, `FileSystemTarget`, `Session`, `InternalRequestEngine`):

``` php
$bootstrap = Bootstrap::$staticObjectManager->get(\TYPO3\Flow\Core\Bootstrap::class);
/* @var Bootstrap $bootstrap */
$requestHandler = $bootstrap->getActiveRequestHandler();
if ($requestHandler instanceof HttpRequestHandlerInterface) {
    $request = $requestHandler->getHttpRequest();
    // ...
}
```

...eeehk
#### HttpRequestHandlerInterface::getRequest()

With 3.3+ it's possible to inject the `HttpRequestHandlerInterface` directly and fetch the current request instance.
Still not a very straight-forward way that still has some potential side-effects

**Comment by bwaidelich** [comment]
## Suggestions

### Incorporate PSR-7

I can't really judge how much work this would mean and if we can do it in a way that won't break everything, but we should consider adhering to the [PSR-7](http://www.php-fig.org/psr/psr-7/) interfaces (and maybe even use one of the existing packages for the request/response implementations)

### Replace RequestHandler with HTTP Component

IMO a good solution for interacting with the "current" request/response would be to make the `Http\ComponentContext`* available as early as possible and allow it to be injected.
The request handling could still be done in the already existing `DispatchComponent` but IMO we don't need the whole `RequestHandler` resolving part.. Using a custom component is easier (see Fluid `AjaxWidgetComponent` for example)

* To be discussed: find a better name that communicates that this is the global HTTP context

**Comment by albe** [comment]
> With 3.3+ it's possible to inject the HttpRequestHandlerInterface directly

Unfortunately not true, because the Http RequestHandler is unproxied and has a constructor dependency

> No difference between incoming and outgoing Request

Good point, though I'm not sure it's worth the effort to separate them.

> make the Http\ComponentContext(*) available as early as possible

That's when the `Http\RequestHandler` kicks in and a `$this->bootstrap->setEarlyInstance(ComponentContext::class, $this->componentContext);` could already do the trick.

> find a better name that communicates that this is the global HTTP context

How about `HttpContext`? ;)

> Incorporate PSR-7

Yes please. I think it's quite doable, a bit of work and of course would be breaking - so it needs to happen with 4.0.


I would also like to discuss if going more towards PSR-15 too instead of ComponentChain would also be plausible. It is still in proposal state, but the direction is quite clear - implement the http kernel as a middleware stack. Currently some middlewares are already in the wild that slightly differ from the PSR-15 spec, but are all pretty equal:
`__invoke($request, $response, $next)`

The main benefit would be to be able to incorporate existing middlewares easily and therefore being able to compose Flows Http behaviour from existing solutions.

**Comment by kitsunet** [comment]
> No difference between incoming and outgoing Request
This is already covered by PSR-7 in the form of `RequestInterface` vs. `ServerRequestInterface`

**Comment by bwaidelich** [comment]
>> With 3.3+ it's possible to inject the HttpRequestHandlerInterface directly

> Unfortunately not true, because the Http RequestHandler is unproxied and has a constructor dependency

oh right, even worse then..

>> No difference between incoming and outgoing Request

> Good point, though I'm not sure it's worth the effort to separate them.

I think it's well worth it and most packages (guzzle, ...) seem to make this distinction. See http://www.php-fig.org/psr/psr-7/#1-5-server-side-requests as well

>>  find a better name that communicates that this is the global HTTP context

> How about HttpContext? ;)

To be honest I think it's better than `ComponentContext` ;)

> I would also like to discuss if going more towards PSR-15 too instead of ComponentChain

I haven't really looked into that and the PSR is still a draft so far.. But yes, worth investigating ofc. Probably we could even implement it without changing our API

**Comment by albe** [comment]
So, since all preparations to move towards PSR-7 have already nicely been done by @kitsunet and we are now moving towards next major, let's start getting things more concrete. 👷 

I started playing a bit with the code, looking what things need to change and how in order to fully make use of PSR-7. Unfortunately, it's not as easy as just replacing our `Http\Request` and `Http\Response` with PSR-7 Implementations (e.g. guzzle) and using those instead.

The first thing I noticed: We need to adapt PSR-17 (http-factory) in order to have true independence of the PSR-7 implementation used. The best implementation I found after a quick search is https://github.com/tuupola/http-factory which automatically instanciates classes of the most common PSR-7 implementations ("This library currently automatically detects and supports zendframework/zend-diactoros, slim/slim, nyholm/psr7 and guzzle/psr7 PSR-7 implementations."). Alternatively, we just copy this couple Factory classes into Flow\Http in case we don't want to depend on this external source.

So wherever we currently create a Http Request, we need to inject a `ServerRequestFactoryInterface`, which we wire towards e.g. tuupola/http-factory or our own via Objects.yaml and then call `createServerRequest`. Correct?

**Comment by albe** [comment]
Started by pushing my current WIP in the PR above. Please take a look at things, it's looking a bit less worse than expected, but still way to go.

**Comment by albe** [comment]
So, current state of affairs:
- PSR-7 is in place in the http package, so we have a distinction between incoming and outgoing request
- PSR-17 factories are available to create new PSR-7 HTTP objects (no more `Request::createFromEnvironment()`, instead the guzzle PSR implementation we use provides a `ServerRequest::fromGlobals` convenience helper)
- To get the *current* request, there still isn't an easy straightforward way in place - you still need the `ComponentContext` or directly fetch from the active `RequestHandler` and check if it is indeed an HTTP RequestHandler. Also, the methods `getHttpRequest` and `getHttpResponse` on the RequestHandler are deprecated, so you should still access them through `getComponentContext()` from there - further improvements in that part will probably happen with PSR-15 (middleware) or when we find a good way to make the `ComponentContext` injectable

**Comment by albe** [comment]
Small late update:
- PSR-15 basis has landed and with it the (temporary?) possibility to simply inject the `ComponentContext` whereever you need it (see https://github.com/neos/flow-development-collection/pull/1928#issuecomment-632266326) - the `ComponentContext` will be removed or at least replaced though, since the `ComponentChain` is deprecated.
- The current Http components need to be phased out and replaced with according PSR-15 middlewares (see #2019)
- We still should adjust our `Browser` implementation to PSR-18 (https://www.php-fig.org/psr/psr-18/), but it currently uses `ServerRequest` for simplicity (see also https://github.com/neos/flow-development-collection/pull/1791)
- also the docs need to be revisited and updated to match the new HTTP internals (see #1994)

**Comment by bwaidelich** [comment]
@albe Thanks for keeping track of the tasks!
I'm not fully into the whole PSR-15 rework yet, so just a question that popped up right now regarding

> the ComponentContext will be removed or at least replaced though, since the ComponentChain is deprecated.

With Flow 6.0 we introduced `HttpRequestHandlerInterface::getComponentContext()`. If we remove this, what would be the equivalent of
```
$this->bootstrap->getActiveRequestHandler()->getComponentContext()->replaceHttpRequest()
```
(or `replaceHttpResponse()`)
?

**Comment by albe** [comment]
I think we have to find out what works/is needed, but out of the box, the replacement would be a middleware. It can invoke the following chain with a new (replaced) HTTP request and/or return a new HTTP response instead of the one returned by the chain.

Generally, you shouldn't replace the response/request at just any arbitrary place. In most cases it makes no sense and in the few cases where it does, it is likely ambiguous and hence error prone.

My idea currently is to replace the `ComponentContext` with an `HttpContext` that allows to get the current request/response, but not alter/replace them. But maybe we don't even need that? For that to work, we'd need to somehow make the middleware chain update the references in the `HttpContext` before/after every single middleware invocation.

**Comment by bwaidelich** [comment]
Btw, I think we should address the new
```
@deprecated Will be removed without replacement with next major
```
comment in `ComponentContext`. Without any additional pointer this is a slap into the face of every dev that wants to implement a custom HTTP component, e.g. to configure some custom routing parameters.

In the meantime I had a quick chat with @albe and I think this is the planned migration path (Alex, please correct me if I got something wrong):

* We'll replace existing HTTP components by corresponding middlewares (#2019)
* We remove the HTTP components from the API but provide some B/C layer (e.g. move it to a separate, optional package or allow it to be activated via Settings)¹
* We provide some core migrations and/or good documentation on how to convert existing components to PSR-15 middleware

Accessing the "current" HTTP request is a common requirement of course but we deprecated `HttpRequestHandlerInterface::getHttpRequest()`.
I think we should revert this deprecation for 7.0.
Furthermore I would suggest to add a very basic factory like

```php
/**
 * @Flow\Scope("singleton")
 */
final class ServerRequestFactory
{

    /**
     * @Flow\Inject
     * @var Bootstrap
     */
    protected $bootstrap;

    public function create(): ServerRequestInterface
    {
        $requestHandler = $this->bootstrap->getActiveRequestHandler();
        if ($requestHandler instanceof HttpRequestHandlerInterface) {
            return $requestHandler->getHttpRequest();
        }
        return ServerRequest::fromGlobals();
    }
}
```

and a couple of lines of `Objects.yaml` configuration:

```yaml
Psr\Http\Message\ServerRequestInterface:
  factoryObjectName: Wwwision\Test\ServerRequestFactory
```

With that, an instance of the ServerRequestInterface can simply be injected. On the CLI (i.e. when there is no active HttpRequestHander) a new instance will be created  in this case..


We still use `ComponentContext::replaceHttpResponse()` in a few places outside of tests & HTTP components in the core:
* [InternalRequestEngine::sendRequest()](https://github.com/neos/flow-development-collection/blob/c805e3141691b1b2e2c8541648ec473ff5e7f6e2/Neos.Flow/Classes/Http/Client/InternalRequestEngine.php#L127) (@albe do you still remember how we planned to replace this one?)
* [ActionResponse::mergeIntoComponentContext()](https://github.com/neos/flow-development-collection/blob/c805e3141691b1b2e2c8541648ec473ff5e7f6e2/Neos.Flow/Classes/Mvc/ActionResponse.php#L269) (the `ComponentContext::setParameter()` in this method has to be replaced as well)

---
¹ as a part of this, we're going to remove `HttpRequestHandlerInterface::getComponentContext()` again. Instead custom parameters can be set/retrieved via `ServerRequestInterface::withAttribute()` & `::getAttribute()`.

**Comment by albe** [comment]
> InternalRequestEngine::sendRequest() (@albe do you still remember how we planned to replace this one?)

By just returning the (error) response from there :) https://github.com/neos/flow-development-collection/blob/c805e3141691b1b2e2c8541648ec473ff5e7f6e2/Neos.Flow/Classes/Http/Client/InternalRequestEngine.php#L137

> Without any additional pointer this is a slap into the face of every dev that wants to implement a custom HTTP component, e.g. to configure some custom routing parameters.

Yeah, that might come across a bit harsh. But it's meant in the sense of "don't expect this to be around any longer". I guess as long as we have a component b/c layer intact, the context will stay around too to be used inside the components.

> Furthermore I would suggest to add a very basic factory like

There already is a `ServerRequestFactory` inside the `Neos.Http.Factories` package. Making that depend on the bootstrap would be backwards and adding another such factory could be confusing? I like the idea to ask the bootstrap::HttpRequestHandlerInterface for an existing HttpRequest

**Comment by bwaidelich** [comment]
> By just returning the (error) response from there :)

Aah, right! :)

> Yeah, that might come across a bit harsh.

I didn't mean the tone, but IMO we should always point to alternatives if we remove an API. In this case there is no real alternative just yet but maybe we should at least point to the issues / documentation of the PSR-15 implementation. We can always add that later of course. I just wanted to create a HTTP component, saw it's deprecation warning and thought "OK, what am I supposed to do now?" :)

> There already is a ServerRequestFactory inside the Neos.Http.Factories package

Yes, true. Probably we can just extend that by a `create()` method

> Making that depend on the bootstrap would be backwards

Why that?
In the end we'll always depend on the bootstrap if we want to get hold of the "current" request, but IMO it's much cleaner not to make the userland code depend on the bootstrap or some request handler.
E.g. consider some EmailService that uses Fluid (and thus needs a HTTP request) to render the email body:

```php
final class EmailService {
  public function __construct(ServicerRequestInterface $httpRequest) { // ...
  }
}
```
would now work in HTTP and CLI context, and it's really easy to test.
If you inject the `bootstrap` instead, you'll need to mock that and the `HttpRequestHandlerInterface` in tests and it wouldn't work in CLI

**Comment by bwaidelich** [comment]
> Probably we can just extend that by a create() method

OK, I forgot that the current [ServerRequestFactory](https://github.com/neos/flow-development-collection/blob/master/Neos.Http.Factories/Classes/ServerRequestFactory.php) is just an implementation of the PSR `ServerRequestFactoryInterface`. We could still extend that of course, but that seems weird.
Also we can't adjust its behavior to return the "current" ServerRequest by default since it's `createServerRequest()` method expects a method and URI to be specified.

Anyways, I don't think we need to reuse that factory at all. We can just create a new one (not implementing the PSR interface and maybe with a better name that somehow communicates that this will return the current http request if it exists)

**Comment by albe** [comment]
> ServerRequestFactory is just an implementation of the PSR ServerRequestFactoryInterface

Exactly.

> maybe with a better name that somehow communicates that this will return the current http request

Naming things... :) I'm open for ideas! `CurrentRequestResolver`? `CurrentRequestInjector`?

**Comment by bwaidelich** [comment]
What do you think of `ActiveServerRequestProvider`? => #2144

**Comment by bwaidelich** [comment]
Closing this one since all depending PRs are merged
