### ISSUE TITLE
rebrand kickstart composer package

### ISSUE THREAD

**Issue by pniederlag** [neos/flow-development-collection#680]
Hi neos,

Is it possible to refactor this package on packagist.org into some flow/neos vendor?
https://packagist.org/packages/typo3/kickstart

Best greets,
Peter

**Comment by kitsunet** [comment]
Hey Peter,

we are preparing to move all packages to neos namespaces (and according package names) in the next release (december) but still the composer names will be used for currently released versions, everything else would be a breaking change. Which means all these keys can only be reused after all currently maintained versions are EOL, at least that's my current understanding. I will check with the others.

**Comment by kitsunet** [comment]
Just to give you an update, we renamed all packages so with the next release this package will become `neos/kickstarter` and the `typo3/kickstart` key will only be in use for older versions. It's still the case though that until the EOL of all released versions using `typo3/kickstart` we cannot release (for reuse) the package key, as otherwise users of it will instead get something else suddenly.

**Comment by pniederlag** [comment]
Hi Christian,
thx :-> 
warm greets to flow/neos,
Peter
