### ISSUE TITLE
FEATURE: Kickstarter command to create basic XLIFF translation files

### ISSUE THREAD

**Issue by daniellienert** [neos/flow-development-collection#880]
As mentioned in http://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartIII/Internationalization.html?highlight=translate#xliff-file-creation a Kickstarter command to generate XLIFF language files would help to start with translating a site.

**Comment by dgrammlich** [comment]
I'll take care of this.

**Comment by dgrammlich** [comment]
Hey @daniellienert,

please have a look at my PR: https://github.com/neos/flow-development-collection/pull/914

Thanks! :)

**Comment by dgrammlich** [comment]
Hi @daniellienert,

I just saw that I used the XLIFF file for the default language as source for the template. The mapping is still missing, every generated file is a default file.
Sorry, I will enhance the command tomorrow and create the mapping file instead of the source file.

@Sebobo mentioned, that we could have a look at the configuration `Neos.Flow.i18n.defaultLocale` and use this for a starting point respectively the default language value. We could use this as default value for the command.

Regards,
Dani
