### ISSUE TITLE
Format lengths for NumbersReader are missing in the CLDR repository

### ISSUE THREAD

**Issue by KaiLehmann** [neos/flow-development-collection#922]
### Description

The main CLDR repository for the path 'numbers/decimalFormats' has no keys for the format length formats that are defined as constants in \Neos\Flow\I18n\Cldr\Reader, such as "const FORMAT_LENGTH_FULL = 'full'".

### Steps to Reproduce

`PropertyMappingConfiguration::setTypeConverterOptions(\Neos\Flow\Property\TypeConverter\FloatConverter::class, array('formatLength' => \Neos\Flow\I18n\Cldr\Reader\NumbersReader::FORMAT_LENGTH_FULL)
`

#### Expected behavior

The property mapping configuration is set.

#### Actual behavior

Exception #1297759968 in line 769 of /[path to file]: Exception while property mapping for target type "[target type]", at property path "[property]": Number format was not found. Please check whether CLDR repository is valid.

### Affected Versions

Flow: 3.0 to 4.0

### More information

Adding this in e.g. /Neos.Flow/Resources/Private/I18n/CLDR/Sources/main/en.xml for the key 'numbers/decimalFormats' resolves the issue for \Neos\Flow\I18n\Cldr\Reader\NumbersReader::FORMAT_LENGTH_FULL:
`
<decimalFormatLength type="full">
  <decimalFormat>
    <pattern>#,##0.###</pattern>
  </decimalFormat>
</decimalFormatLength>
`

**Comment by albe** [comment]
Hey there, thanks for the report. The issue here is, that the CLDR data is directly taken from http://cldr.unicode.org, so patching that data in Flow to fit specific use cases is not an option unfortunately.

I think the solution here would rather be to handle the exception and fall back to another format length.

**Comment by albe** [comment]
Closing as wontfix, since this is an issue with the data provided in the CLDR rather than the framework.
According to the DTD the format length values are valid: `<attributeValues elements="dateFormatLength timeFormatLength dateTimeFormatLength decimalFormatLength scientificFormatLength percentFormatLength currencyFormatLength" attributes="type" order="given">full long medium short</attributeValues>`
